[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "18" }

[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "all"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
